# Generated by Django 5.1.3 on 2024-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Mulai Program'),
        ),
    ]
