# Generated by Django 5.1.3 on 2024-12-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_child_akta_kelahiran_child_ktp'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
