# Generated by Django 5.1.3 on 2024-12-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_riwayatkegiatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sosial Emosional', 'Sosial Emosional'), ('Kognitif', 'Kognitif'), ('Motorik', 'Motorik'), ('Bahasa', 'Bahasa')], max_length=50)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Mulai Berkembang', 'Mulai Berkembang'), ('Belum Berkembang', 'Belum Berkembang')], max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='users.child')),
            ],
        ),
    ]
