# Generated by Django 5.1.3 on 2024-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_childdevelopment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiwayatKegiatan',
        ),
    ]
