# Generated by Django 5.1.3 on 2024-12-13 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0017_alter_pendaftaran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
